#!/bin/sh
#
# Make FDD disk image
# 128 bytes/sector, 26 sectors/track, 76 tracks/disk
#

if [ $# -ne 1 ];
then
   echo "usage: mkfdd <filename>"
   exit 1
fi

dd if=/dev/zero of=$1 bs=128 count=1976

# vim:ts=3 sw=3 et:
